### PR TITLE
Bump nunjucks version

### PR DESCRIPTION
**Pull request by jameswragg**
From 2.4.2 to 3.1.7

### CODE REVIEW

**Comment by c1rrus** [comment]
Hah! I was literally about to make a PR for the exact same thing. :-)
I hope the maintainers accept and release this soon.

**Comment by allmarkedup** [comment]
@jameswragg thanks for this - however do you think you could revert the version number change in your PR? We are going to release a v2.0.0 of this adapter due to a [breaking change in the merge behaviour](https://github.com/frctl/nunjucks/pull/6) and it'd make more sense to include this in the same release - especially if Nunjucks 2.4.2 -> 3.1.7 includes any breaking changes (which I assume it does?)

**Comment by jameswragg** [comment]
@allmarkedup done

**Comment by allmarkedup** [comment]
@jameswragg awesome, many thanks - merging now 👍

**Comment by jameswragg** [comment]
@allmarkedup any chance you can publish to npm?

**Comment by allmarkedup** [comment]
@jameswragg sorry about the delay! I've just published this now. It's worth noting the breaking changes in the README when you upgrade - and if you run into any problems just let me know.

**Pull request merged**
